/*
 * Copyright (C) 2026 Hal Hildebrand. All rights reserved.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package com.hellblazer.luciferase.lucien.pyramid;

import com.hellblazer.luciferase.lucien.HybridElement;
import com.hellblazer.luciferase.lucien.entity.LongEntityID;
import com.hellblazer.luciferase.lucien.entity.SequentialLongIDGenerator;
import com.hellblazer.luciferase.lucien.tetree.Tet;
import com.hellblazer.luciferase.lucien.tetree.TetreeConnectivity;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.vecmath.Point3i;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * RDR-010 Luciferase-2l04: <b>deep</b> pyramid-rooted tet ({@code minTetLevel < level}) EDGE/VERTEX
 * cross-shape neighbors. cjwr Phase B made deep tets reachable as keys; 2l04 widens
 * {@code PyramidNeighborDetector.allShapeNeighbors} to enumerate tet candidates at every pyramidal-branch
 * depth, so a deep-tet query (and deep-tet neighbors) are surfaced.
 *
 * <p>The headline check is an <b>independent whole-domain completeness oracle</b>: the element universe is
 * generated by real refinement ({@link Pyramid#child}/{@link Tet#child}) — a code path entirely separate
 * from the detector's 27-cube enumerate-and-filter — and a deep-tet query's vertex-neighbor set is
 * required to contain every universe element sharing ≥ 1 vertex. This closes the symmetric-miss blind
 * spot <b>for EDGE/VERTEX adjacency</b> (the {@code sharedVertexCount ≥ 1} criterion) that reciprocity
 * alone cannot catch — addressing the EDGE/VERTEX half of cjwr Phase A substantive-critic SIG-2.
 *
 * <p><b>Not closed here:</b> the deep FACE tet-vs-pyramid classification false-negative (the other half
 * of SIG-2). A Bey-SFC tet face neighbor can share 0 vertices with the query, so this vertex oracle
 * cannot validate it; deep face correctness is covered (positively) by {@code HybridFaceNeighborTest}'s
 * conforming-geometry + involution checks, but an independent face-completeness oracle remains future
 * work.
 *
 * @author hal.hildebrand
 */
class PyramidDeepCrossShapeEdgeVertexTest {

    private static final int LEVEL = 3;

    private PyramidNeighborDetector detector;

    @BeforeEach
    void setUp() {
        detector = (PyramidNeighborDetector) new PyramidIndex<LongEntityID, String>(
            new SequentialLongIDGenerator()).getNeighborDetector();
    }

    /** All SFC elements at exactly {@code LEVEL}, generated by real refinement from the two roots. */
    private List<HybridElement> universeAtLevel() {
        var out = new ArrayList<HybridElement>();
        var stack = new ArrayDeque<HybridElement>();
        stack.push(new Pyramid(0, 0, 0, (byte) 0, Pyramid.TYPE_6));
        stack.push(new Pyramid(0, 0, 0, (byte) 0, Pyramid.TYPE_7));
        while (!stack.isEmpty()) {
            var e = stack.pop();
            if (e.level() == LEVEL) {
                out.add(e);
                continue;
            }
            if (e instanceof Pyramid p) {
                for (int i = 0; i < TetreeConnectivity.CHILDREN_PER_PYRAMID; i++) {
                    stack.push(p.child(i));
                }
            } else {
                var t = (Tet) e;
                for (int i = 0; i < TetreeConnectivity.CHILDREN_PER_TET; i++) {
                    stack.push(t.child(i));
                }
            }
        }
        return out;
    }

    private static Point3i[] verts(HybridElement e) {
        return e instanceof Pyramid p ? p.coordinates() : ((Tet) e).coordinates();
    }

    private static int sharedVertexCount(Point3i[] a, Point3i[] b) {
        int shared = 0;
        for (var pa : a) {
            for (var pb : b) {
                if (pa.equals(pb)) {
                    shared++;
                    break;
                }
            }
        }
        return shared;
    }

    private static boolean isDeepTet(HybridElement e) {
        return e instanceof Tet t && t.minTetLevel() != Tet.NO_TET_ANCESTOR && t.minTetLevel() < t.level();
    }

    @Test
    void deepTetVertexNeighborsAreCompleteVsWholeDomainRefinement() {
        var universe = universeAtLevel();
        var keys = new ArrayList<PyramidKey>(universe.size());
        for (var e : universe) {
            keys.add(e instanceof Pyramid p ? PyramidKeyCodec.encode(p) : PyramidKeyCodec.encode((Tet) e));
        }

        var deepQueries = 0;
        var totalChecks = 0;
        for (int q = 0; q < universe.size(); q++) {
            if (!isDeepTet(universe.get(q)) || keys.get(q) == null) {
                continue;
            }
            deepQueries++;
            var found = new HashSet<>(detector.findVertexNeighbors(keys.get(q)));
            var qVerts = verts(universe.get(q));
            for (int i = 0; i < universe.size(); i++) {
                if (i == q || keys.get(i) == null) {
                    continue;
                }
                if (sharedVertexCount(qVerts, verts(universe.get(i))) >= 1) {
                    assertTrue(found.contains(keys.get(i)),
                               "deep-tet vertex enumeration missed a whole-domain vertex-sharing element: "
                               + "query=" + universe.get(q) + " missing=" + universe.get(i));
                    totalChecks++;
                }
            }
        }
        assertTrue(deepQueries > 0, "must exercise deep-tet queries (got 0)");
        // A deep tet shares each of its 4 vertices with several universe elements; require a healthy
        // average so an accidental under-reporting regression is visible, not just >= 1 per query.
        assertTrue(totalChecks >= deepQueries * 4,
                   "deep-tet queries must have multiple vertex-sharing neighbors each, got " + totalChecks
                   + " over " + deepQueries + " queries");
    }

    @Test
    void deepTetEdgeVertexNeighborsAreReciprocalAndNested() {
        var universe = universeAtLevel();
        var reciprocityChecks = 0;
        for (var e : universe) {
            if (!isDeepTet(e)) {
                continue;
            }
            var qk = PyramidKeyCodec.encode((Tet) e);
            if (qk == null) {
                continue;
            }
            var faces = new HashSet<>(detector.findFaceNeighbors(qk));
            var edges = new HashSet<>(detector.findEdgeNeighbors(qk));
            var verts = new HashSet<>(detector.findVertexNeighbors(qk));
            // face ⊆ edge ⊆ vertex for a deep-tet query.
            assertTrue(edges.containsAll(faces), "face ⊆ edge for deep tet " + qk);
            assertTrue(verts.containsAll(edges), "edge ⊆ vertex for deep tet " + qk);
            // Reciprocity: every vertex neighbor lists the deep-tet query back.
            for (var nk : verts) {
                assertTrue(detector.findVertexNeighbors(nk).contains(qk),
                           "deep-tet vertex adjacency must be reciprocal: " + qk + " <-> " + nk);
                if (edges.contains(nk)) {
                    assertTrue(detector.findEdgeNeighbors(nk).contains(qk),
                               "deep-tet edge adjacency must be reciprocal: " + qk + " <-> " + nk);
                }
                reciprocityChecks++;
            }
        }
        assertTrue(reciprocityChecks >= 5,
                   "deep-tet queries must surface (reciprocal) edge/vertex neighbors, got " + reciprocityChecks);
    }

    @Test
    void deepTetQueryHasDeepTetNeighbors() {
        // Non-vacuity for the NEW capability: a deep-tet query must surface at least one DEEP-tet neighbor
        // (not only pyramids/shallow tets), proving the deep candidate enumeration actually contributes.
        var universe = universeAtLevel();
        var deepNeighborSeen = false;
        for (var e : universe) {
            if (!isDeepTet(e)) {
                continue;
            }
            var qk = PyramidKeyCodec.encode((Tet) e);
            if (qk == null) {
                continue;
            }
            for (var nk : detector.findVertexNeighbors(qk)) {
                if (isDeepTet(PyramidIndex.elementFromKey(nk))) {
                    deepNeighborSeen = true;
                    break;
                }
            }
            if (deepNeighborSeen) {
                break;
            }
        }
        assertTrue(deepNeighborSeen, "a deep-tet query must surface at least one deep-tet vertex neighbor");
    }
}
