name: Update Performance Documentation

on:
  push:
    branches: [main]
    paths:
      - 'lucien/src/**/*.java'
      - 'lucien/pom.xml'
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force documentation update even without changes'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  performance-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
        
    - name: Build all modules
      run: |
        mvn clean compile test-compile
        
    - name: Run OctreeVsTetreeVsPrismBenchmark
      run: |
        mvn test -Dtest=OctreeVsTetreeVsPrismBenchmark -DRun_SPATIAL_INDEX_PERF_TESTS=true -DfailIfNoTests=false -pl lucien
        
    - name: Extract Performance Data
      run: |
        # Extract data from test output
        mvn exec:java -Dexec.mainClass="com.hellblazer.luciferase.lucien.performance.TestResultExtractor" \
          -Dexec.args="lucien/target/surefire-reports lucien/target/performance-results.csv" \
          -Dexec.classpathScope=test -pl lucien
          
    - name: Update Documentation
      run: |
        mvn exec:java -Dexec.mainClass="com.hellblazer.luciferase.lucien.performance.RobustPerformanceUpdater" \
          -Dexec.args="lucien/target/performance-results.csv" \
          -Dexec.classpathScope=test -pl lucien
          
    - name: Check for changes
      id: verify-changed-files
      run: |
        git diff --name-only > changed-files.txt
        if [ -s changed-files.txt ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Changed files:"
          cat changed-files.txt
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No documentation changes detected"
        fi
        
    - name: Commit documentation updates
      if: steps.verify-changed-files.outputs.has_changes == 'true'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add lucien/doc/PERFORMANCE_METRICS_MASTER.md
        git add lucien/doc/performance-data/*.csv || true
        git commit -m "Auto-update performance metrics [skip ci]
        
        Updated from commit: ${{ github.sha }}
        Triggered by: ${{ github.event_name }}"
        
    - name: Push changes
      if: steps.verify-changed-files.outputs.has_changes == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
    - name: Log Performance Test Failure
      if: failure()
      run: |
        echo "⚠️ Performance tests failed in commit ${{ github.sha }}"
        echo "Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Please check the logs above and update performance metrics manually if needed."